#!/bin/bash
#
# Title:      Reference Title File - PGBlitz
# Author(s):  Admin9705 & https://github.com/PGBlitz/PGClone/graphs/contributors - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: include PGClone aliases
      include_tasks: '/opt/pgclone/ymls/alias.yml'

    - debug: msg="Combined Path - {{multihds}}"

    - name: Install Union Script
      template:
        src: /opt/pgclone/source/local.sh
        dest: /opt/rclone/pgunity.sh
        force: yes

    - name: Install PGUnity Service
      template:
        src: /opt/pgclone/mounts/pgunity.service
        dest: /etc/systemd/system/pgunity.service
        force: yes

    - name: Reload PGUnity Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: pgunity

    - name: Sleep 2 Seconds
      wait_for: timeout=2

    - name: Restart All Docker Containers
      shell: docker restart $(docker ps -a -q)
